fix slack notification

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -32,7 +32,6 @@ jobs:
       - name: Configure Git
         run: |
           git config --global url."https://${{ secrets.PULUMI_BOT_TOKEN }}:x-oauth-basic@github.com/pulumi/pulumi-hugo-internal".insteadOf "https://github.com/pulumi/pulumi-hugo-internal"
-
       - name: Install assume-role
         run: go install github.com/remind101/assume-role@latest
 
@@ -61,7 +60,7 @@ jobs:
           name: origin-bucket-metadata
           path: origin-bucket-metadata.json
   notify:
-    if: github.ref == 'refs/heads/master' && failure()
+    if: (github.ref == 'refs/heads/master' || (github.event_name == 'pull_request' && github.event.pull_request.user.login == 'pulumi-bot')) && failure()
     name: Send slack notification
     runs-on: ubuntu-latest
     needs: [buildSite]
